### ISSUE TITLE
Can't change channels from Source List

### ISSUE THREAD

**Issue by dapper2490** [bertbert72/HomeAssistant_VirginTivo#106]
Is anyone else unable to change channels from the source list?  There was a recent firmware update from Tivo that I suspect may be causing the issue.  I'm still getting all the programme info, and can send remote commends but no channel changes.

**Comment by simontay75** [comment]
Hi dapper2490, 

I can also confirm the problem here on my setup on both my V6 boxes, however I have used the telnet interface manually for many years and I can also confirm that it's stopped working in that, suggesting it's a change on the V6 boxes and not a fault of this plugin.

If you telnet to your tivo on port 31339 you connect directly to it.
The command is SETCH <channel number> e.g. SETCH 101

When I do that now, I get the error: 

CH_FAILED NO_LIVE

Source of information about how it works (not sure if I'm allowed to post a link - please redact if not)
https://www.tivocommunity.com/threads/tivo-ui-control-via-telnet-no-hacking-required.392385/

CH_FAILED NO_LIVE means the TIVO thinks it's not on live TV, e.g. watching netflix etc.
This says to me something has changed on the Tivo boxes.

There is a possible fix - you can still set the channel using IRCODES.

So for example, to set BBC1 (Channel 101) the correct method is SETCH 101 which we know fails, but:

IRCODE NUM1
IRCODE NUM0
IRCODE NUM1

Would dial channel 101 and emulate presses on a remote control. This does work, so a quick change to the code by a competent programmer (not me!!) could make it work again. I'd rather share what little I've found, and if it's wrong apologies. I think there might be a very quick fix for this.

**Comment by simontay75** [comment]
I have got it working by editing media_player.py.

I made the following changes:

Line 945 from:

        cmd = "SETCH " + str(channel_id) + "\r"
        self.tivo_cmd(cmd)

to:

        cmd = "SETCH " + str(channel_id) + "\r"             
        strchannel = str(channel_id)
        cmd = "IRCODE NUM" + strchannel[0] + "\r"
        self.tivo_cmd(cmd)
        cmd = "IRCODE NUM" + strchannel[1] + "\r" 
        self.tivo_cmd(cmd)
        cmd = "IRCODE NUM" + strchannel[2] + "\r"
        self.tivo_cmd(cmd)

I know the top line is unnecessary, but I left it in so I can easily find the code in the future if I need to revert it.

I set strchannel to str(channel_id). I then set cmd to "IRCODE NUM" and specify the first digit in the string [0]
Send the command,
do it again but this time with the second value [1]
Send the command,
and lastly do it again with the third value [2]
Send the command.

I've now got a working tivo from the source list again. 

I am not a python programmer, I just read the code and worked out how to change it. Perhaps the owners of the code, if they agree this is the way forward, could make the changes properly? 

Really - if this a problem with V6 firmware changes, Virgin should be told and asked to put it back.

Hope this helps someone.

**Comment by snapper2472** [comment]
Works a treat simontay75. Thanks

**Comment by grewhit25** [comment]
Yep works for me.

**Comment by bertbert72** [comment]
Thanks @simontay75.  I'm not actively using HA so don't have an easy way of finding or fixing new issues.  Feel free to do a pull request if you have fixed anything else and I'll merge it.
