### ISSUE TITLE
Is it possible to utilize force_hd but only for certain channels?

### ISSUE THREAD

**Issue by bfayers** [bertbert72/HomeAssistant_VirginTivo#24]
BBC do not broadcast local broadcasts on HD channels 😠 just wondering if I can utilize force_hd but exclude BBC One?

**Comment by bertbert72** [comment]
Assuming you are using the tvchannellists option, then you just need to set an override for BBC One.  Have a look at the override section in example1.yaml.

It might actually be exactly what you're after.  In it, I'm overriding BBC One (101) and BBC One (108) so that the component knows that 108 is the HD version.  

If that doesn't help, let me know what your current configuration is and some more details on what you're trying to achieve.

**Comment by bertbert72** [comment]
Closing due to no further information in 30 days.  Feel free to re-open if you still need any assistance.
