### ISSUE TITLE
Media Access Key

### ISSUE THREAD

**Issue by richard-scott** [bertbert72/HomeAssistant_VirginTivo#36]
Hi,

My VM v6 box now requires a [Media Access Key](https://www.broadbandchoices.co.uk/providers/virgin-media/how-to-set-up-virgin-tv-anywhere#_where_can_i_find_my_media_access_key_for_my_virgin_media_tivo_box_) to grant network access to control it.

I can only assume VM pushed out a new update to its firmware in the last week while I was away as it worked just fine before. Now I have no control ;-(

Thanks,

Richard.

**Comment by richard-scott** [comment]
Ignore that, it doesn't work for some other reason. Not sure what yet ;-(
I'm on 0.97.2

**Comment by bertbert72** [comment]
I was going to wait until I got home to have a look to see if I'd got any update.  I would have been surprised if the MAK was suddenly required since we're not accessing any content.  There's another setting for Network Control in the Virgin system menu (somewhere!).  That needs to be set on.  Maybe if your box has reset itself, that has been disabled.  Pretty sure the default setting is off.  Worth checking.  

I'm running 0.97.1 but it's unlikely the minor patch release broke anything.
