### ISSUE TITLE
Media Play state is always off

### ISSUE THREAD

**Issue by kevindbeard** [bertbert72/HomeAssistant_VirginTivo#40]
Even though the on/off button works on the media player control, the state never changes from "off".

I have a V6 box.

**Comment by bertbert72** [comment]
Can you provide your logs and your configuration?

**Comment by kevindbeard** [comment]
Hi, thanks for the reply.  I've never submitted this sort of info before.  Should I set any particular log level, as there is no mention of tivo in /config/home-assistant.log

Also, what config do you need? My configuration.yaml?

**Comment by bertbert72** [comment]
No mention of tivo in the log isn't a good sign to start with!  The bit of your configuration.yaml I need is just the bit relating to the Tivo setup.  

If you aren't currently getting anything in the logs, might be worth sticking on debug, although it is quite verbose.  If you still don't get anything, it would appear the component isn't actually installed.

```
logger:
  logs:
    custom_components.media_player.virgintivo: debug

```

**Comment by kevindbeard** [comment]
[home-assistant.log](https://github.com/bertbert72/HomeAssistant_VirginTivo/files/4204046/home-assistant.log)

from configuration.yaml

media_player:
  - platform: braviatv
    host: 192.168.0.149
    name: "Sony TV"
  - platform: virgintivo
    tivos:
      1:
        name: Virgin Box
        host: 192.168.0.11
        keep_connected: true
    tvchannellists:
      enable: true

**Comment by kevindbeard** [comment]
Interestingly, I just rebooted after dropping the logging. Then I powered on the tivo via HA. That worked and I briefly saw what channel it was on in HA. Then it went back to thinking the tivo was off.

**Comment by bertbert72** [comment]
So from the log, the component is able to make a connection to the Tivo at IP 192.168.0.11.  Since you haven't overridden the ports, it'll use the default (31339) and so it's not likely that this is accidentally connecting to something else.  

However no reponse is being received from any commands so the component marks the Tivo as off, which is the normal reason why that happens.  The other usual reason is that you're not on live TV, e.g. playing a recording.  Which I assume isn't the case?

The other possibility would be that you haven't enabled network remote control on the V6.  Could you check that has been done?

As another bit of debugging you could remove/disable the component and try making a manual connection to the Tivo using telnet or Putty and seeing whether you are getting any reponses.

**Comment by bertbert72** [comment]
One other thing you could try would be to remove this line:

`keep_connected: true`

This is a historical artifact from when I wanted to avoid continually connecting and disconnecting from the Tivo.  In practice the overhead isn't much so the current default is to have this as false.  It can interfere with other systems that want to use the same interface.  Maybe it is actually blocking itself somehow.

**Comment by kevindbeard** [comment]
Sorry for the delay. Thanks for the suggestions.  

I removed the keep_connected option and rebooted and now it seems to be working.

I'll close this now.  Thanks so much

**Comment by quickclix75** [comment]
> One other thing you could try would be to remove this line:
> 
> `keep_connected: true`
> 
> This is a historical artifact from when I wanted to avoid continually connecting and disconnecting from the Tivo. In practice the overhead isn't much so the current default is to have this as false. It can interfere with other systems that want to use the same interface. Maybe it is actually blocking itself somehow.

Can the above be removed from the example files if its been deprecated please? Took me a while to figure this one out when I was setting up until I found this thread.. Ta
