### ISSUE TITLE
Turns off when using apps (ie, Netflix)

### ISSUE THREAD

**Issue by vinceemail** [bertbert72/HomeAssistant_VirginTivo#64]
This works wonderfully, except tivo media players in home assistant seem to turn 'off' when watching video via an app - in my case, Netflix. 

I'd love to use this as a fully integrated replacement for my Chromecast, which will turn on my AV equipment via an automation when the media player is in use. For this to work, I would need the device to show as on whenever it is not in standby. 

Thanks.

**Comment by bertbert72** [comment]
Unfortunately this is a limitation of the telnet interface we have to use with the Virigin boxes.  When you move away from live TV (e.g. into an app, or a recording) they stop giving statuses.  This is indistinguishable from the box being on standby.

A compromise might be to introduce another setting where users can optionally choose whether we mark the box as off when this happens.  The first problem, which may mean this is useless for you, is that the box will then never show as off, even when it is.  The other problem is that since the box is providing no info, I wouldn't have any clue what is happening or what channel is might be on behind the scenes.  But I'll have a look.  Could be a while though as I'm not currently resident at home so don't have access to the Tivos.

**Comment by vinceemail** [comment]
Ah, interesting! I did worry this might be the case.

I suppose if we went with that route, it would be the same as using a standard 'dumb' remote, in that the remote can fire on off, and button commands, but cannot tell the state of the device. That may still be useful. 

Is there a list of telnet commands online anywhere? Perhaps I could take a look and have a think 🤔

**Comment by bertbert72** [comment]
You can find a copy of the telnet protocol commands here:

https://github.com/RogueProeliator/IndigoPlugin-TiVo-Network-Remote/blob/master/Documentation/TiVo_TCP_Network_Remote_Control_Protocol.pdf
