### ISSUE TITLE
Parsing error on channel list

### ISSUE THREAD

**Issue by ColinRobbins** [bertbert72/HomeAssistant_VirginTivo#83]
I am seeing a new parsing error this morning:
```
Logger: custom_components.virgintivo.media_player
Source: custom_components/virgintivo/media_player.py:1147
Integration: virgintivo (documentation)
First occurred: 11:10:06 (1 occurrences)
Last logged: 11:10:06

Could not fetch channel listings from https://www.tvchannellists.com/List_of_channels_on_Virgin_Media_(UK)_-_New_Packages, error invalid literal for int() with base 10: '01/06/21'
```

**Comment by ColinRobbins** [comment]
It looks like the format of the channel listing has changed.
In some cases there is a date in the first column.
The pull request check for this, and ignores the row.
Might want to do something better to handle the exception, but this allow the integration to restart at least.

**Comment by bertbert72** [comment]
Thanks for spotting this and also for the PR.  The problem is that they've added an extra table which doesn't have anything to do with the channels themselves.  It's a reformatting of the upcoming channel changes notes.  A slightly more robust option would be to only process the tables that refer to TV and Radio (i.e. have HD/SD at the start).  There's no point bothering to process each line in a table that we can't understand.

I've still not managed to get around to rebuilding my server so can't test this properly, but if you could try the new branch at 

https://github.com/bertbert72/HomeAssistant_VirginTivo/tree/fix-extra-table

that would be very helpful. Thanks

**Comment by ColinRobbins** [comment]
Yes, that branch seems to resolve the issue.
I’d still recommend my additional check, so it adds some robustness for any future changes they may make.
Thanks.

**Comment by richard-scott** [comment]
I've just applied this patch to fix my installation. I can confirm it works (for now). 
I've been Googling for an RSS Feed of channels, but not yet found a decent one.

**Comment by richard-scott** [comment]
I spoke to sone, it has stopped again:

```
This error originated from a custom integration.

Logger: custom_components.virgintivo.media_player
Source: custom_components/virgintivo/media_player.py:1150
Integration: virgintivo (documentation)
First occurred: 22:24:07 (1 occurrences)
Last logged: 22:24:07

Could not fetch channel listings from https://www.tvchannellists.com/List_of_channels_on_Virgin_Media_(UK)_-_New_Packages, error list index out of range
```
